version: '3'

services:
  nuxt:
    build:
      context: .
    depends_on:
    - db
    - ipfs
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      API_HOST: http://localhost:3000
      CDN_HOST: http://localhost:8080
      HOST: 0.0.0.0
      IPFS_HOST: http://ipfs:5001
      IPFS_MASTER: http://ipfs:5001
      LIKECHAIN_HOST: ${LIKECHAIN_HOST}
      LIKECHAIN_STORAGE_PROVIDER: puttyimages
      LIKECOIN_AUTH_URL: https://api.rinkeby.like.co/api/users/challenge
      PROVIDER_ADDRESS: ${PROVIDER_ADDRESS}
      PROVIDER_PRIVATE_KEY: $(PROVIDER_PRIVATE_KEY)

  db:
    image: postgres:10.4
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  ipfs:
    image: ipfs/go-ipfs:v0.4.15
    ports:
      - "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs

volumes:
  db_data:
    driver: local
  ipfs_data:
    driver: local
